#Numpad1::Run "D:\1. Document"
#Numpad2::Run "D:\2. Source"
#Numpad3::Run "D:\3. Test"
#Numpad4::Run "D:\4. Release"
#Numpad5::Run "D:\5. Util"
#Numpad6::Run "D:\6. VM"
#x::WinClose, A
#c::Run "calc.exe"
#m::Run "stikynot.exe"
#n::Run "notepad.exe"
#p::Run "mspaint.exe"